grails-app/controllers/basic/CarController.groovy
package basic

import basic.users.*
import grails.plugin.springsecurity.annotation.Secured

@Secured(['ROLE_ADMIN'])
class CarController {
	static scaffold = true

	def springSecurityService
	def addCarService
	
	def showListOfCars(User inputUser) {
		def user = springSecurityService.currentUser
		
		if (user == null) {
			user = inputUser
		}
		
		Employee admin = Employee.findByUser(user)

		def carList = admin.store.cars
		return [carList:carList]
	}

	def addCar(User inputUser) {
		def user = springSecurityService.currentUser 

		if (user == null) {
			user = inputUser
		}
		
		def i = addCarService.add(params.price, params.manufacturer, params.description, user)
		
		if (i == 0) {
			flash.error = "error"
		}
	}
}

grails-app/views/layouts/administration.gsp
<g:applyLayout name="custom">
	<title><g:layoutTitle default="Benzo"/></title>
	<g:layoutBody/>
	<content tag="menu">
		<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
		<li><g:link action="index"><g:message code="reservationAssignment.assignments_link" /></g:link></li>
		<li><g:link action="showListOfReservations"><g:message code="reservationAssignment.reservationlist_link" /></g:link></li>
	</content>
</g:applyLayout>

grails-app/views/layouts/basic.gsp
<g:applyLayout name="custom">
	<title><g:layoutTitle default="Benzo"/></title>
	<g:layoutBody/>
	<content tag="menu">
		<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
		<li><g:link controller="employee" action="index"><g:message code="employee.add.label" /></g:link></li>

		<li><g:link controller="employee" action="showListOfEmployees"><g:message code="employeeCreation.employeelist_link" /></g:link></li>

		<li><g:link controller="car" action="showListOfCars"><g:message code="car.car_list" /></g:link></li>

		<li><g:link controller="car" action="index"><g:message code="car.creation.label" /></g:link></li>
		
		<li><g:link controller="store" action="showListOfAllStores"><g:message code="store.seeAll_link" /></g:link></li>
		<li><g:link controller="store" action="index"><g:message code="store.create_store_link" /></g:link></li>
	</content>
</g:applyLayout>

grails-app/views/layouts/custom.gsp
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"><!--<![endif]-->
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<title><g:layoutTitle default="Benzo"/></title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="shortcut icon" href="${assetPath(src: 'favicon.ico')}" type="image/x-icon">
		<link rel="apple-touch-icon" href="${assetPath(src: 'apple-touch-icon.png')}">
		<link rel="apple-touch-icon" sizes="114x114" href="${assetPath(src: 'apple-touch-icon-retina.png')}">
  		<link href='https://fonts.googleapis.com/css?family=Open+Sans:400italic,400,700' rel='stylesheet' type='text/css'>
		
		<asset:stylesheet src="jquery-ui.min.css"/>
		<asset:stylesheet src="style.css" media="screen"/>
		<asset:stylesheet src="print.css" media="print"/>
		
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
		<asset:javascript src="jquery-ui.min.js"/>
		<asset:javascript src="script.js"/>
		<g:layoutHead/>
	</head>
	<body>
		<div id="container">
			<div id="header">
				<div id="logo">
					<g:img dir="images" file="logo.png" style="width:140px;"/>
				</div>
				<nav>
					<div id="languages">
						<sec:ifLoggedIn>						
							<g:form controller="logout" action="index" >
								<g:submitButton name="create" value="${message(code: 'default.logout.label', default: 'Logout')}" class="logout" />
							</g:form>
						</sec:ifLoggedIn>
						<a href="?lang=da" class="da" title="Danish"><asset:image src="Denmark-icon.png" alt="Danish"/></a>
						<a href="?lang=en" class="EN" title="English (UK)"><asset:image src="United-Kingdom-icon.png" alt="English (UK)"/></a>
						<a href="?lang=bih" class="BIH" title="Bosnian"><asset:image src="Bosnia-icon.png" alt="English (UK)"/></a>
					</div>
					<ul>
						<g:pageProperty name="page.menu"/>
					</ul>
				</nav>
			</div>
			<div id="body">
				<div>
					<g:layoutBody/>
				</div>
			</div>
			<footer>
				&copy; Benzo 2015
			</footer>
			<div id="spinner" class="spinner" style="display:none;"><g:message code="spinner.alt" default="Loading&hellip;"/></div>
		</div>
	</body>
</html>

grails-app/views/layouts/main.gsp
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"><!--<![endif]-->
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<title><g:layoutTitle default="Benzo"/></title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="shortcut icon" href="${assetPath(src: 'favicon.ico')}" type="image/x-icon">
		<link rel="apple-touch-icon" href="${assetPath(src: 'apple-touch-icon.png')}">
		<link rel="apple-touch-icon" sizes="114x114" href="${assetPath(src: 'apple-touch-icon-retina.png')}">
  		<link href='https://fonts.googleapis.com/css?family=Open+Sans:400italic,400,700' rel='stylesheet' type='text/css'>
		<asset:stylesheet src="style.css" media="screen"/>
		<asset:stylesheet src="print.css" media="print"/>
		<asset:javascript src="application.js"/>
		<g:layoutHead/>
	</head>
	<body>
		<div id="container">
			<div id="header">
				<nav>
					<ul>
						<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
						<li><g:link controller="employee" action="showProfile"><g:message code="employee.profile" /></g:link></li>
					</ul>
					<div id="languages">
						<sec:ifLoggedIn>
							<g:form controller="logout" action="index" >
								<g:submitButton name="create" value="${message(code: 'default.logout.label', default: 'Logout')}" class="logout" />
							</g:form>
						</sec:ifLoggedIn>
						<a href="?lang=da" class="da" title="Danish"><asset:image src="Denmark-icon.png" alt="Danish"/></a>
						<a href="?lang=en" class="EN" title="English (UK)"><asset:image src="United-Kingdom-icon.png" alt="English (UK)"/></a>
						<a href="?lang=bih" class="BIH" title="Bosnian"><asset:image src="Bosnia-icon.png" alt="English (UK)"/></a>
					</div>
				</nav>
			</div>
			<div id="body">
				<div>
					<g:layoutBody/>
				</div>
			</div>
			<footer>
				&copy; Benzo 2015
			</footer>
		</div>
	</body>
</html>

grails-app/views/layouts/reservation.gsp
<g:applyLayout name="custom">
	<title><g:layoutTitle default="Benzo"/></title>
	<g:layoutBody/>
	<content tag="menu">
		<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
		<!--<li><g:link controller= "reservation" action="reserver"><g:message code="store.create_reservation.label" /></g:link></li>-->
	</content>
</g:applyLayout>