grails-app/domain/administration/Employeeassignment.groovy
package administration

import basic.Employee
import ordering.Reservation

class Employeeassignment {
	Employee employee
	Reservation reservation
	
}

grails-app/controllers/administration/EmployeeassignmentController.groovy
package administration

import basic.Employee
import basic.Store
import basic.users.User
import ordering.Reservation
import basic.EmployeeType
import basic.StoreType

import grails.plugin.springsecurity.annotation.Secured

@Secured(['ROLE_ADMIN', 'ROLE_STAFF'])
class EmployeeassignmentController {
	AssignService assignService
	def springSecurityService
	ShowListOfReservationsService showListOfReservationsService

	@Secured(['ROLE_ADMIN'])
	def index() {
		return [employeeassignmentInstanceList:Employeeassignment.findAll()]
	}
	
	@Secured(['ROLE_ADMIN'])
	def showListOfReservations(User inputUser) {
		def user = springSecurityService.currentUser
		
		if (user == null) {
			user = inputUser
		}
		
		Employee admin = Employee.findByUser(User.findById(user.id))
		return showListOfReservationsService.showReservationList(admin)
	}

	@Secured(['ROLE_ADMIN'])
 	def showListOfEmployees(Reservation reservation) {
		def employeeList = []
		
		Closure makeList = { EmployeeType et -> 
						for (employee in Store.findById(reservation.store.id).employees) {
							if (employee.type == et) {
							   employeeList << employee
							}
						}
					}

		if (reservation.store.type == StoreType.REPAIRS) {
			makeList(EmployeeType.MECHANIC)
		} else if (reservation.store.type == StoreType.SALES) {
			makeList(EmployeeType.SALESMAN)
		}

		return [employees:employeeList]
	}
	@Secured(['ROLE_ADMIN'])
	def assign() {
		Reservation reservation = Reservation.findById(params.reservation)
		Employee employee = Employee.findById(params.employee)	
		assignService.assignment(reservation, employee)
	}
}

grails-app/views/employeeassignment/_form.gsp
<%@ page import="administration.Employeeassignment" %>



<div class="fieldcontain ${hasErrors(bean: employeeassignmentInstance, field: 'employee', 'error')} required">
	<label for="employee">
		<g:message code="employeeassignment.employee.label" default="Employee" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="employee" name="employee.id" from="${basic.Employee.list()}" optionKey="id" required="" value="${employeeassignmentInstance?.employee?.id}" class="many-to-one"/>

</div>

<div class="fieldcontain ${hasErrors(bean: employeeassignmentInstance, field: 'reservation', 'error')} required">
	<label for="reservation">
		<g:message code="employeeassignment.reservation.label" default="Reservation" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="reservation" name="reservation.id" from="${ordering.Reservation.list()}" optionKey="id" required="" value="${employeeassignmentInstance?.reservation?.id}" class="many-to-one"/>

</div>

grails-app/views/employeeassignment/assign.gsp
<%@ page import="administration.Employeeassignment" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="administration">
		<g:set var="entityName" value="${message(code: 'employeeassignment.label', default: 'Employeeassignment')}" />
		<g:set var="employee" value="${message(code: 'employee.label', default: 'Employee')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<h1><g:message code="reservationAssignment.reservation_assignment_completed" /></h1>
		<g:message code="reservationAssignment.reservation_assignment_completed_message" />
		<a href="index"><g:message code="default.back.label"  default="Go back"/></a>
	</body>
</html>

grails-app/views/employeeassignment/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="custom">
		<g:set var="entityName" value="${message(code: 'employeeassignment.label', default: 'Employeeassignment')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-employeeassignment" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-employeeassignment" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${employeeassignmentInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${employeeassignmentInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:employeeassignmentInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/employeeassignment/edit.gsp
<%@ page import="administration.Employeeassignment" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'employeeassignment.label', default: 'Employeeassignment')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-employeeassignment" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-employeeassignment" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${employeeassignmentInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${employeeassignmentInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:employeeassignmentInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${employeeassignmentInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/employeeassignment/index.gsp
<%@ page import="administration.Employeeassignment" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="administration">
		<g:set var="entityName" value="${message(code: 'employeeassignment.label', default: 'Employeeassignment')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<h1><g:message code="default.list.label" args="[entityName]" /></h1>
		<article>
			<div id="list-employeeassignment" class="content scaffold-list" role="main">
				<g:if test="${flash.message}">
					<div class="message" role="status">${flash.message}</div>
				</g:if>
				<table>
					<thead>
						<tr>
							<th><g:message code="employeeassignment.employee.label" default="Employee" /></th>
							<th><g:message code="employeeassignment.reservation.label" default="Reservation" /></th>
							<th><g:message code="reservation.date.label" default="Date" /></th>
						</tr>
					</thead>
					<tbody>
					<g:each in="${employeeassignmentInstanceList}" status="i" var="employeeassignmentInstance">
						<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
							<td>${fieldValue(bean: employeeassignmentInstance, field: "employee")}</td>
							<td>${fieldValue(bean: employeeassignmentInstance, field: "reservation")}</td>
							<td><g:formatDate format="dd-MM/yyyy" date="${employeeassignmentInstance.reservation.date}"/></td>
						</tr>
					</g:each>
					</tbody>
				</table>
			</div>
		</article>
	</body>
</html>

grails-app/views/employeeassignment/show.gsp
<%@ page import="administration.Employeeassignment" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'employeeassignment.label', default: 'Employeeassignment')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-employeeassignment" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-employeeassignment" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list employeeassignment">
			
				<g:if test="${employeeassignmentInstance?.employee}">
				<li class="fieldcontain">
					<span id="employee-label" class="property-label"><g:message code="employeeassignment.employee.label" default="Employee" /></span>
					
						<span class="property-value" aria-labelledby="employee-label"><g:link controller="employee" action="show" id="${employeeassignmentInstance?.employee?.id}">${employeeassignmentInstance?.employee?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${employeeassignmentInstance?.reservation}">
				<li class="fieldcontain">
					<span id="reservation-label" class="property-label"><g:message code="employeeassignment.reservation.label" default="Reservation" /></span>
					
						<span class="property-value" aria-labelledby="reservation-label"><g:link controller="reservation" action="show" id="${employeeassignmentInstance?.reservation?.id}">${employeeassignmentInstance?.reservation?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:employeeassignmentInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${employeeassignmentInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/employeeassignment/showListOfEmployees.gsp
<%@ page import="administration.Employeeassignment" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="administration">
		<g:set var="entityName" value="${message(code: 'employeeassignment.label', default: 'Employeeassignment')}" />
		<g:set var="employee" value="${message(code: 'employee.label', default: 'Employee')}" />
		<title><g:message code="reservationAssignment.employeelist" args="[entityName]" /></title>
	</head>
	<body>
		<h1><g:message code="reservationAssignment.employeelist" /></h1>
		<article class="reservation">
			<g:form url="[resource:employeeassignmentInstance, action:'assign']" >
				<g:hiddenField name="reservation" value="${params?.id}"/>
				<fieldset class="form">
					<label for="employee">
						<g:message code="reservationAssignment.choose_employee" default="Choose a car" />:
					</label>
					<select name="employee">
						<g:each in="${employees}" var="Employee">
							<option value="${Employee.id}">${Employee.name}</option>
						</g:each>
					</select>
				</fieldset>
				<br>
				<fieldset class="buttons">
					<g:submitButton name="create" value="${message(code: 'default.button.assign.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</article>
	</body>
</html>

grails-app/views/employeeassignment/showListOfReservations.gsp
<%@ page import="administration.Employeeassignment" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="administration">
		<g:set var="entityName" value="${message(code: 'employeeassignment.label', default: 'Employeeassignment')}" />
		<g:set var="employee" value="${message(code: 'employee.label', default: 'Employee')}" />
		<title><g:message code="reservationAssignment.reservationlist" args="[entityName]" /></title>
	</head>
	<body>
		<h1><g:message code="reservationAssignment.reservationlist" /></h1>
		<g:each in="${reservations}" var="Reservation">
			<article class="reservation">
				<label><g:message code="store.label" />:</label>${Reservation.store.name}<br/>
				<label><g:message code="car.label" />:</label>${Reservation.car.manufacturer}<br/>
				<label><g:message code="reservation.date.label" />:</label><g:formatDate format="dd-MM/yyyy" date="${Reservation.date}"/>
				<a href="showListOfEmployees/${Reservation.id}"><g:message code="default.assign.label" args="[employee]"/></a>
			</article>
		</g:each>
	</body>
</html>